development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
#  database: roscontrol_development
  database: roscontrol_dev
  pool: 5
  username: root
  password: 
  host: localhost
#  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: roscontrol_test
  pool: 5
  username: root
  password: 
  host: localhost
#  socket: /var/run/mysqld/mysqld.sock
  
  
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: roscontrol_production
  pool: 5
  username: root
  password: 
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
